import type { BffClient } from './BffClient';
import type {
  BffRoicOptionsRequest,
  BffRoicOptionsResponse,
  BffRoicDataRequest,
  BffRoicDataResponse,
  BffRoicSimpleInputRequest,
  BffRoicSimpleInputResponse,
  BffRoicSimpleInputSaveRequest,
  BffRoicSimpleInputSaveResponse,
} from '../types';

// モックデータ
const mockOptions: BffRoicOptionsResponse = {
  mode: 'STANDARD',
  fiscalYears: [
    { fiscalYear: 2025, label: '2025年度' },
    { fiscalYear: 2024, label: '2024年度' },
  ],
  budgetEvents: [
    {
      id: 'evt-001',
      eventCode: 'BUDGET_2025',
      eventName: '2025年度当初予算',
      scenarioType: 'BUDGET',
      fiscalYear: 2025,
      hasFixedVersion: true,
    },
  ],
  forecastEvents: [
    {
      id: 'evt-002',
      eventCode: 'FC_2025_Q3',
      eventName: '2025年度Q3見込',
      scenarioType: 'FORECAST',
      fiscalYear: 2025,
      hasFixedVersion: true,
    },
  ],
  versions: {
    'evt-001': [
      {
        id: 'ver-001',
        versionCode: 'V1',
        versionName: 'V1 確定版',
        versionNo: 1,
        status: 'FIXED',
      },
    ],
    'evt-002': [
      {
        id: 'ver-002',
        versionCode: 'V1',
        versionName: 'V1 確定版',
        versionNo: 1,
        status: 'FIXED',
      },
    ],
  },
  departments: [
    {
      id: 'dept-001',
      stableId: 'CORP',
      name: '全社',
      code: '0000',
      level: 0,
      hasChildren: true,
      children: [
        {
          id: 'dept-002',
          stableId: 'DIV_A',
          name: '事業部A',
          code: '1000',
          level: 1,
          hasChildren: true,
          children: [
            {
              id: 'dept-003',
              stableId: 'SALES_1',
              name: '営業1課',
              code: '1100',
              level: 2,
              hasChildren: false,
            },
            {
              id: 'dept-004',
              stableId: 'SALES_2',
              name: '営業2課',
              code: '1200',
              level: 2,
              hasChildren: false,
            },
          ],
        },
        {
          id: 'dept-005',
          stableId: 'DIV_B',
          name: '事業部B',
          code: '2000',
          level: 1,
          hasChildren: false,
        },
      ],
    },
  ],
  roicPlLayoutId: 'layout-pl-001',
  roicPlLayoutName: 'ROIC用PLレイアウト',
  roicBsLayoutId: 'layout-bs-001',
  roicBsLayoutName: 'ROIC用BSレイアウト',
  waccRate: 0.08,
  effectiveTaxRate: 0.3,
  isConfigComplete: true,
  missingConfigItems: [],
};

const mockData: BffRoicDataResponse = {
  mode: 'STANDARD',
  kpis: [
    // Tier 1
    {
      id: 'roic',
      name: 'ROIC',
      originalValue: 0.085,
      simulatedValue: 0.085,
      compareValue: 0.075,
      unit: '%',
      isCalculable: true,
      format: 'percent',
      displayPriority: 1,
    },
    {
      id: 'wacc',
      name: 'WACC',
      originalValue: 0.08,
      simulatedValue: 0.08,
      compareValue: 0.08,
      unit: '%',
      isCalculable: true,
      format: 'percent',
      displayPriority: 1,
    },
    {
      id: 'roicSpread',
      name: 'ROICスプレッド',
      originalValue: 0.005,
      simulatedValue: 0.005,
      compareValue: -0.005,
      unit: '%',
      isCalculable: true,
      format: 'percent',
      displayPriority: 1,
    },
    {
      id: 'nopat',
      name: 'NOPAT',
      originalValue: 85000000,
      simulatedValue: 85000000,
      compareValue: 75000000,
      unit: '円',
      isCalculable: true,
      format: 'currency',
      displayPriority: 1,
    },
    // Tier 2
    {
      id: 'nopatRate',
      name: 'NOPAT率',
      originalValue: 0.085,
      simulatedValue: 0.085,
      compareValue: 0.075,
      unit: '%',
      isCalculable: true,
      format: 'percent',
      displayPriority: 2,
    },
    {
      id: 'capitalTurnover',
      name: '資本回転率',
      originalValue: 1.0,
      simulatedValue: 1.0,
      compareValue: 1.0,
      unit: '回',
      isCalculable: true,
      format: 'rate',
      displayPriority: 2,
    },
    {
      id: 'investedCapital',
      name: '投下資本',
      originalValue: 1000000000,
      simulatedValue: 1000000000,
      compareValue: 1000000000,
      unit: '円',
      isCalculable: true,
      format: 'currency',
      displayPriority: 2,
    },
    {
      id: 'ebit',
      name: 'EBIT',
      originalValue: 121428571,
      simulatedValue: 121428571,
      compareValue: 107142857,
      unit: '円',
      isCalculable: true,
      format: 'currency',
      displayPriority: 2,
    },
    // Tier 3
    {
      id: 'operatingAssets',
      name: '営業資産',
      originalValue: 1500000000,
      simulatedValue: 1500000000,
      compareValue: 1500000000,
      unit: '円',
      isCalculable: true,
      format: 'currency',
      displayPriority: 3,
    },
    {
      id: 'operatingLiabilities',
      name: '営業負債',
      originalValue: 500000000,
      simulatedValue: 500000000,
      compareValue: 500000000,
      unit: '円',
      isCalculable: true,
      format: 'currency',
      displayPriority: 3,
    },
    {
      id: 'effectiveTaxRate',
      name: '実効税率',
      originalValue: 0.3,
      simulatedValue: 0.3,
      compareValue: 0.3,
      unit: '%',
      isCalculable: true,
      format: 'percent',
      displayPriority: 3,
    },
  ],
  tree: [
    {
      lineId: 'roic',
      lineNo: 1,
      lineType: 'header',
      displayName: 'ROIC',
      subjectId: null,
      indentLevel: 0,
      isEditable: false,
      isAdjustment: false,
      originalValue: 0.085,
      compareValue: 0.075,
      parentLineId: null,
      childLineIds: ['nopat', 'invested_capital'],
      rollupCoefficient: 1,
      section: 'roic',
    },
    {
      lineId: 'nopat',
      lineNo: 2,
      lineType: 'account',
      displayName: 'NOPAT',
      subjectId: 'subj-nopat',
      indentLevel: 1,
      isEditable: false,
      isAdjustment: false,
      originalValue: 85000000,
      compareValue: 75000000,
      parentLineId: 'roic',
      childLineIds: ['ebit', 'tax_factor'],
      rollupCoefficient: 1,
      section: 'nopat',
    },
    {
      lineId: 'ebit',
      lineNo: 3,
      lineType: 'account',
      displayName: 'EBIT',
      subjectId: 'subj-ebit',
      indentLevel: 2,
      isEditable: true,
      isAdjustment: false,
      originalValue: 121428571,
      compareValue: 107142857,
      parentLineId: 'nopat',
      childLineIds: [],
      rollupCoefficient: 1,
      section: 'nopat',
    },
    {
      lineId: 'tax_factor',
      lineNo: 4,
      lineType: 'note',
      displayName: '(1 - 実効税率)',
      subjectId: null,
      indentLevel: 2,
      isEditable: false,
      isAdjustment: false,
      originalValue: 0.7,
      compareValue: 0.7,
      parentLineId: 'nopat',
      childLineIds: [],
      rollupCoefficient: 1,
      section: 'nopat',
    },
    {
      lineId: 'invested_capital',
      lineNo: 5,
      lineType: 'account',
      displayName: '投下資本',
      subjectId: 'subj-ic',
      indentLevel: 1,
      isEditable: false,
      isAdjustment: false,
      originalValue: 1000000000,
      compareValue: 1000000000,
      parentLineId: 'roic',
      childLineIds: ['operating_assets', 'operating_liabilities'],
      rollupCoefficient: 1,
      section: 'invested_capital',
    },
    {
      lineId: 'operating_assets',
      lineNo: 6,
      lineType: 'account',
      displayName: '営業資産',
      subjectId: 'subj-oa',
      indentLevel: 2,
      isEditable: true,
      isAdjustment: false,
      originalValue: 1500000000,
      compareValue: 1500000000,
      parentLineId: 'invested_capital',
      childLineIds: [],
      rollupCoefficient: 1,
      section: 'invested_capital',
    },
    {
      lineId: 'operating_liabilities',
      lineNo: 7,
      lineType: 'account',
      displayName: '営業負債',
      subjectId: 'subj-ol',
      indentLevel: 2,
      isEditable: true,
      isAdjustment: false,
      originalValue: 500000000,
      compareValue: 500000000,
      parentLineId: 'invested_capital',
      childLineIds: [],
      rollupCoefficient: -1,
      section: 'invested_capital',
    },
  ],
  roicVsWaccChart: {
    points: [
      {
        period: 'Q1',
        label: 'Q1',
        roicOriginal: 0.082,
        roicSimulated: 0.082,
        roicCompare: 0.072,
        wacc: 0.08,
      },
      {
        period: 'Q2',
        label: 'Q2',
        roicOriginal: 0.084,
        roicSimulated: 0.084,
        roicCompare: 0.074,
        wacc: 0.08,
      },
      {
        period: 'Q3',
        label: 'Q3',
        roicOriginal: 0.086,
        roicSimulated: 0.086,
        roicCompare: 0.076,
        wacc: 0.08,
      },
      {
        period: 'Q4',
        label: 'Q4',
        roicOriginal: 0.088,
        roicSimulated: 0.088,
        roicCompare: 0.078,
        wacc: 0.08,
      },
    ],
    isSinglePoint: false,
    waccRate: 0.08,
  },
  decompositionChart: {
    original: { nopatRate: 0.085, capitalTurnover: 1.0, roic: 0.085 },
    simulated: { nopatRate: 0.085, capitalTurnover: 1.0, roic: 0.085 },
    compare: { nopatRate: 0.075, capitalTurnover: 1.0, roic: 0.075 },
  },
  warnings: [],
  bsSubstitutedWithActual: false,
};

const mockSimpleInput: BffRoicSimpleInputResponse = {
  operatingAssets: [
    {
      subjectId: 'oa-001',
      subjectCode: '1100',
      subjectName: '営業資産計',
      indentLevel: 0,
      isEditable: false,
      isAggregate: true,
      parentSubjectId: null,
      h1Value: 750000000,
      h2Value: 800000000,
      annualValue: 775000000,
    },
    {
      subjectId: 'oa-002',
      subjectCode: '1110',
      subjectName: '売掛金',
      indentLevel: 1,
      isEditable: true,
      isAggregate: false,
      parentSubjectId: 'oa-001',
      h1Value: 300000000,
      h2Value: 320000000,
      annualValue: 310000000,
    },
    {
      subjectId: 'oa-003',
      subjectCode: '1120',
      subjectName: '棚卸資産',
      indentLevel: 1,
      isEditable: true,
      isAggregate: false,
      parentSubjectId: 'oa-001',
      h1Value: 450000000,
      h2Value: 480000000,
      annualValue: 465000000,
    },
  ],
  operatingLiabilities: [
    {
      subjectId: 'ol-001',
      subjectCode: '2100',
      subjectName: '営業負債計',
      indentLevel: 0,
      isEditable: false,
      isAggregate: true,
      parentSubjectId: null,
      h1Value: 250000000,
      h2Value: 280000000,
      annualValue: 265000000,
    },
    {
      subjectId: 'ol-002',
      subjectCode: '2110',
      subjectName: '買掛金',
      indentLevel: 1,
      isEditable: true,
      isAggregate: false,
      parentSubjectId: 'ol-001',
      h1Value: 200000000,
      h2Value: 220000000,
      annualValue: 210000000,
    },
    {
      subjectId: 'ol-003',
      subjectCode: '2120',
      subjectName: '未払費用',
      indentLevel: 1,
      isEditable: true,
      isAggregate: false,
      parentSubjectId: 'ol-001',
      h1Value: 50000000,
      h2Value: 60000000,
      annualValue: 55000000,
    },
  ],
  eventId: 'evt-simple-001',
  versionId: 'ver-simple-001',
};

export class MockBffClient implements BffClient {
  private delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  async getOptions(
    _request: BffRoicOptionsRequest
  ): Promise<BffRoicOptionsResponse> {
    await this.delay(300);
    return mockOptions;
  }

  async getData(_request: BffRoicDataRequest): Promise<BffRoicDataResponse> {
    await this.delay(500);
    return mockData;
  }

  async getSimpleInput(
    _request: BffRoicSimpleInputRequest
  ): Promise<BffRoicSimpleInputResponse> {
    await this.delay(300);
    return mockSimpleInput;
  }

  async saveSimpleInput(
    _request: BffRoicSimpleInputSaveRequest
  ): Promise<BffRoicSimpleInputSaveResponse> {
    await this.delay(500);
    return {
      success: true,
      eventId: 'evt-simple-001',
      versionId: 'ver-simple-001',
    };
  }
}
